export default function Spinner() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      style={{
        background: "transparent",
        display: "block",
        shapeRendering: "auto",
      }}
      width="64px"
      height="64px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <g transform="rotate(0 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-2.2916666666666665s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(30 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-2.083333333333333s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(60 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-1.8749999999999998s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(90 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-1.6666666666666665s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(120 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-1.458333333333333s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(150 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-1.2499999999999998s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(180 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-1.0416666666666665s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(210 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-0.8333333333333333s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(240 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-0.6249999999999999s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(270 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-0.41666666666666663s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(300 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="-0.20833333333333331s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(330 50 50)">
        <rect
          x="47"
          y="24"
          rx="2.88"
          ry="2.88"
          width="6"
          height="12"
          fill="#000000"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="2.5s"
            begin="0s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
    </svg>
  );
}
